.code
	PUSH 80			contract Message {\n\taddress ...
	PUSH 40			contract Message {\n\taddress ...
	MSTORE 			contract Message {\n\taddress ...
	CALLVALUE 			function Message(address _regi...
	DUP1 			olidity 0
	ISZERO 			a 
	PUSH [tag] 1			a 
	JUMPI 			a 
	PUSH 0			p
	DUP1 			S
	REVERT 			24;\n\n//Simpl
tag 1			a 
	JUMPDEST 			a 
	POP 			function Message(address _regi...
	PUSH 40			function Message(address _regi...
	MLOAD 			function Message(address _regi...
	PUSHSIZE 			function Message(address _regi...
	CODESIZE 			function Message(address _regi...
	SUB 			function Message(address _regi...
	DUP1 			function Message(address _regi...
	PUSHSIZE 			function Message(address _regi...
	DUP4 			function Message(address _regi...
	CODECOPY 			function Message(address _regi...
	DUP2 			function Message(address _regi...
	ADD 			function Message(address _regi...
	PUSH 40			function Message(address _regi...
	SWAP1 			function Message(address _regi...
	DUP2 			function Message(address _regi...
	MSTORE 			function Message(address _regi...
	DUP2 			function Message(address _regi...
	MLOAD 			function Message(address _regi...
	PUSH 20			function Message(address _regi...
	DUP1 			function Message(address _regi...
	DUP5 			function Message(address _regi...
	ADD 			function Message(address _regi...
	MLOAD 			function Message(address _regi...
	SWAP3 			function Message(address _regi...
	DUP5 			function Message(address _regi...
	ADD 			function Message(address _regi...
	MLOAD 			function Message(address _regi...
	PUSH 60			function Message(address _regi...
	DUP6 			function Message(address _regi...
	ADD 			function Message(address _regi...
	MLOAD 			function Message(address _regi...
	PUSH 0			registrar
	DUP1 			registrar=_registrar
	SLOAD 			registrar=_registrar
	PUSH 1			
	PUSH A0			
	PUSH 2			
	EXP 			
	SUB 			
	DUP1 			registrar=_registrar
	DUP8 			registrar=_registrar
	AND 			registrar=_registrar
	PUSH 1			
	PUSH A0			
	PUSH 2			
	EXP 			
	SUB 			
	NOT 			
	SWAP3 			registrar=_registrar
	DUP4 			registrar=_registrar
	AND 			registrar=_registrar
	OR 			registrar=_registrar
	SWAP1 			registrar=_registrar
	SWAP3 			registrar=_registrar
	SSTORE 			registrar=_registrar
	PUSH 1			registrar=_registrar
	DUP1 			from=_from
	SLOAD 			from=_from
	DUP4 			from=_from
	DUP10 			from=_from
	AND 			from=_from
	SWAP1 			from=_from
	DUP4 			from=_from
	AND 			from=_from
	OR 			from=_from
	SWAP1 			from=_from
	SSTORE 			from=_from
	PUSH 2			to
	DUP1 			to=_to
	SLOAD 			to=_to
	SWAP3 			to=_to
	DUP6 			to=_to
	AND 			to=_to
	SWAP3 			to=_to
	SWAP1 			to=_to
	SWAP2 			to=_to
	AND 			to=_to
	SWAP2 			to=_to
	SWAP1 			to=_to
	SWAP2 			to=_to
	OR 			to=_to
	SWAP1 			to=_to
	SSTORE 			to=_to
	SWAP1 			function Message(address _regi...
	SWAP5 			function Message(address _regi...
	ADD 			function Message(address _regi...
	DUP1 			hash_msg=_hash_msg
	MLOAD 			hash_msg=_hash_msg
	SWAP3 			function Message(address _regi...
	SWAP5 			function Message(address _regi...
	SWAP3 			function Message(address _regi...
	SWAP1 			function Message(address _regi...
	SWAP2 			function Message(address _regi...
	PUSH [tag] 4			hash_msg=_hash_msg
	SWAP2 			hash_msg=_hash_msg
	PUSH 3			hash_msg
	SWAP2 			hash_msg
	DUP5 			hash_msg=_hash_msg
	ADD 			hash_msg=_hash_msg
	SWAP1 			hash_msg=_hash_msg
	PUSH [tag] 5			hash_msg=_hash_msg
	JUMP [in]			hash_msg=_hash_msg
tag 4			hash_msg=_hash_msg
	JUMPDEST 			hash_msg=_hash_msg
	POP 			
	POP 			
	TIMESTAMP 			now
	PUSH 5			timestamp_msg
	SSTORE 			timestamp_msg=now
	POP 			
	PUSH [tag] 6			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	POP 			
	POP 			
	JUMP 			contract Message {\n\taddress ...
tag 5			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	SLOAD 			contract Message {\n\taddress ...
	PUSH 1			contract Message {\n\taddress ...
	DUP2 			contract Message {\n\taddress ...
	PUSH 1			contract Message {\n\taddress ...
	AND 			contract Message {\n\taddress ...
	ISZERO 			contract Message {\n\taddress ...
	PUSH 100			contract Message {\n\taddress ...
	MUL 			contract Message {\n\taddress ...
	SUB 			contract Message {\n\taddress ...
	AND 			contract Message {\n\taddress ...
	PUSH 2			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	DIV 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	PUSH 0			contract Message {\n\taddress ...
	MSTORE 			contract Message {\n\taddress ...
	PUSH 20			contract Message {\n\taddress ...
	PUSH 0			contract Message {\n\taddress ...
	KECCAK256 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	PUSH 1F			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	PUSH 20			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	DIV 			contract Message {\n\taddress ...
	DUP2 			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	SWAP3 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	PUSH 1F			contract Message {\n\taddress ...
	LT 			contract Message {\n\taddress ...
	PUSH [tag] 8			contract Message {\n\taddress ...
	JUMPI 			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	MLOAD 			contract Message {\n\taddress ...
	PUSH FF			contract Message {\n\taddress ...
	NOT 			contract Message {\n\taddress ...
	AND 			contract Message {\n\taddress ...
	DUP4 			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	OR 			contract Message {\n\taddress ...
	DUP6 			contract Message {\n\taddress ...
	SSTORE 			contract Message {\n\taddress ...
	PUSH [tag] 10			contract Message {\n\taddress ...
	JUMP 			contract Message {\n\taddress ...
tag 8			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	PUSH 1			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	DUP6 			contract Message {\n\taddress ...
	SSTORE 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	ISZERO 			contract Message {\n\taddress ...
	PUSH [tag] 10			contract Message {\n\taddress ...
	JUMPI 			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
tag 9			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	DUP2 			contract Message {\n\taddress ...
	GT 			contract Message {\n\taddress ...
	ISZERO 			contract Message {\n\taddress ...
	PUSH [tag] 10			contract Message {\n\taddress ...
	JUMPI 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	MLOAD 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	SSTORE 			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	PUSH 20			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	PUSH 1			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	PUSH [tag] 9			contract Message {\n\taddress ...
	JUMP 			contract Message {\n\taddress ...
tag 10			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	POP 			
	PUSH [tag] 11			contract Message {\n\taddress ...
	SWAP3 			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	POP 			
	PUSH [tag] 12			contract Message {\n\taddress ...
	JUMP [in]			contract Message {\n\taddress ...
tag 11			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	POP 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	JUMP [out]			contract Message {\n\taddress ...
tag 12			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	PUSH [tag] 13			contract Message {\n\taddress ...
	SWAP2 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
tag 14			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	DUP3 			contract Message {\n\taddress ...
	GT 			contract Message {\n\taddress ...
	ISZERO 			contract Message {\n\taddress ...
	PUSH [tag] 11			contract Message {\n\taddress ...
	JUMPI 			contract Message {\n\taddress ...
	PUSH 0			contract Message {\n\taddress ...
	DUP2 			contract Message {\n\taddress ...
	SSTORE 			contract Message {\n\taddress ...
	PUSH 1			contract Message {\n\taddress ...
	ADD 			contract Message {\n\taddress ...
	PUSH [tag] 14			contract Message {\n\taddress ...
	JUMP 			contract Message {\n\taddress ...
tag 13			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	SWAP1 			contract Message {\n\taddress ...
	JUMP [out]			contract Message {\n\taddress ...
tag 6			contract Message {\n\taddress ...
	JUMPDEST 			contract Message {\n\taddress ...
	PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Message {\n\taddress ...
	DUP1 			contract Message {\n\taddress ...
	PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Message {\n\taddress ...
	PUSH 0			contract Message {\n\taddress ...
	CODECOPY 			contract Message {\n\taddress ...
	PUSH 0			contract Message {\n\taddress ...
	RETURN 			contract Message {\n\taddress ...
.data
	0:
		.code
			PUSH 80			contract Message {\n\taddress ...
			PUSH 40			contract Message {\n\taddress ...
			MSTORE 			contract Message {\n\taddress ...
			PUSH 4			contract Message {\n\taddress ...
			CALLDATASIZE 			contract Message {\n\taddress ...
			LT 			contract Message {\n\taddress ...
			PUSH [tag] 1			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			PUSH FFFFFFFF			contract Message {\n\taddress ...
			PUSH 100000000000000000000000000000000000000000000000000000000			contract Message {\n\taddress ...
			PUSH 0			contract Message {\n\taddress ...
			CALLDATALOAD 			contract Message {\n\taddress ...
			DIV 			contract Message {\n\taddress ...
			AND 			contract Message {\n\taddress ...
			PUSH 1E68CBB			contract Message {\n\taddress ...
			DUP2 			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 2			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH 13151981			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 3			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH 2B20E397			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 4			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH 7EC0F30D			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 5			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH 8BDC558D			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 6			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH 8D6F24D4			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 7			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH D5CE3389			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 8			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			PUSH EAA9B9A7			contract Message {\n\taddress ...
			EQ 			contract Message {\n\taddress ...
			PUSH [tag] 9			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
		tag 1			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			CALLVALUE 			contract Message {\n\taddress ...
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 10			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 10			a 
			JUMPDEST 			a 
			POP 			contract Message {\n\taddress ...
			PUSH 0			0
			CALLVALUE 			msg.value
			GT 			msg.value>0
			ISZERO 			if(msg.value>0) {\n\t\t\tif(ms...
			PUSH [tag] 15			if(msg.value>0) {\n\t\t\tif(ms...
			JUMPI 			if(msg.value>0) {\n\t\t\tif(ms...
			PUSH 1			from
			SLOAD 			from
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			AND 			from
			CALLER 			msg.sender
			EQ 			msg.sender==from
			ISZERO 			if(msg.sender==from) {\t\t\t\n...
			PUSH [tag] 14			if(msg.sender==from) {\t\t\t\n...
			JUMPI 			if(msg.sender==from) {\t\t\t\n...
			PUSH 2			to
			SLOAD 			to
			PUSH 40			to.send(msg.value)
			MLOAD 			to.send(msg.value)
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			SWAP1 			to
			SWAP2 			to
			AND 			to
			SWAP1 			to
			CALLVALUE 			msg.value
			DUP1 			to.send(msg.value)
			ISZERO 			to.send(msg.value)
			PUSH 8FC			to.send(msg.value)
			MUL 			to.send(msg.value)
			SWAP2 			to.send(msg.value)
			PUSH 0			to
			DUP2 			to.send(msg.value)
			DUP2 			to
			DUP2 			to.send(msg.value)
			DUP6 			msg.value
			DUP9 			to
			DUP9 			to.send(msg.value)
			CALL 			to.send(msg.value)
			SWAP4 			to.send(msg.value)
			POP 			to.send(msg.value)
			POP 			to.send(msg.value)
			POP 			to.send(msg.value)
			POP 			to.send(msg.value)
			POP 			to.send(msg.value)
			PUSH [tag] 15			if(msg.sender==from) {\t\t\t\n...
			JUMP 			if(msg.sender==from) {\t\t\t\n...
		tag 14			if(msg.sender==from) {\t\t\t\n...
			JUMPDEST 			if(msg.sender==from) {\t\t\t\n...
			PUSH 1			from
			SLOAD 			from
			PUSH 40			from.send(msg.value)
			MLOAD 			from.send(msg.value)
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			SWAP1 			from
			SWAP2 			from
			AND 			from
			SWAP1 			from
			CALLVALUE 			msg.value
			DUP1 			from.send(msg.value)
			ISZERO 			from.send(msg.value)
			PUSH 8FC			from.send(msg.value)
			MUL 			from.send(msg.value)
			SWAP2 			from.send(msg.value)
			PUSH 0			from
			DUP2 			from.send(msg.value)
			DUP2 			from
			DUP2 			from.send(msg.value)
			DUP6 			msg.value
			DUP9 			from
			DUP9 			from.send(msg.value)
			CALL 			from.send(msg.value)
			POP 			
			POP 			
			POP 			
			POP 			
			POP 			
		tag 15			if(msg.sender==from) {\t\t\t\n...
			JUMPDEST 			if(msg.sender==from) {\t\t\t\n...
			STOP 			contract Message {\n\taddress ...
		tag 2			uint256 public timestamp_msg
			JUMPDEST 			uint256 public timestamp_msg
			CALLVALUE 			uint256 public timestamp_msg
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 16			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 16			a 
			JUMPDEST 			a 
			POP 			uint256 public timestamp_msg
			PUSH [tag] 17			uint256 public timestamp_msg
			PUSH [tag] 18			uint256 public timestamp_msg
			JUMP 			uint256 public timestamp_msg
		tag 17			uint256 public timestamp_msg
			JUMPDEST 			uint256 public timestamp_msg
			PUSH 40			uint256 public timestamp_msg
			DUP1 			uint256 public timestamp_msg
			MLOAD 			uint256 public timestamp_msg
			SWAP2 			uint256 public timestamp_msg
			DUP3 			uint256 public timestamp_msg
			MSTORE 			uint256 public timestamp_msg
			MLOAD 			uint256 public timestamp_msg
			SWAP1 			uint256 public timestamp_msg
			DUP2 			uint256 public timestamp_msg
			SWAP1 			uint256 public timestamp_msg
			SUB 			uint256 public timestamp_msg
			PUSH 20			uint256 public timestamp_msg
			ADD 			uint256 public timestamp_msg
			SWAP1 			uint256 public timestamp_msg
			RETURN 			uint256 public timestamp_msg
		tag 3			address public to
			JUMPDEST 			address public to
			CALLVALUE 			address public to
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 19			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 19			a 
			JUMPDEST 			a 
			POP 			address public to
			PUSH [tag] 20			address public to
			PUSH [tag] 21			address public to
			JUMP 			address public to
		tag 20			address public to
			JUMPDEST 			address public to
			PUSH 40			address public to
			DUP1 			address public to
			MLOAD 			address public to
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			SWAP1 			address public to
			SWAP3 			address public to
			AND 			address public to
			DUP3 			address public to
			MSTORE 			address public to
			MLOAD 			address public to
			SWAP1 			address public to
			DUP2 			address public to
			SWAP1 			address public to
			SUB 			address public to
			PUSH 20			address public to
			ADD 			address public to
			SWAP1 			address public to
			RETURN 			address public to
		tag 4			address public registrar
			JUMPDEST 			address public registrar
			CALLVALUE 			address public registrar
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 22			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 22			a 
			JUMPDEST 			a 
			POP 			address public registrar
			PUSH [tag] 20			address public registrar
			PUSH [tag] 24			address public registrar
			JUMP 			address public registrar
		tag 5			function ack(string _hash) {\n...
			JUMPDEST 			function ack(string _hash) {\n...
			CALLVALUE 			function ack(string _hash) {\n...
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 25			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 25			a 
			JUMPDEST 			a 
			POP 			
			PUSH 40			function ack(string _hash) {\n...
			DUP1 			function ack(string _hash) {\n...
			MLOAD 			function ack(string _hash) {\n...
			PUSH 20			function ack(string _hash) {\n...
			PUSH 4			function ack(string _hash) {\n...
			DUP1 			function ack(string _hash) {\n...
			CALLDATALOAD 			function ack(string _hash) {\n...
			DUP1 			function ack(string _hash) {\n...
			DUP3 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			CALLDATALOAD 			function ack(string _hash) {\n...
			PUSH 1F			function ack(string _hash) {\n...
			DUP2 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			SWAP1 			function ack(string _hash) {\n...
			DIV 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			MUL 			function ack(string _hash) {\n...
			DUP6 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			SWAP1 			function ack(string _hash) {\n...
			SWAP6 			function ack(string _hash) {\n...
			MSTORE 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			MSTORE 			function ack(string _hash) {\n...
			PUSH [tag] 15			function ack(string _hash) {\n...
			SWAP5 			function ack(string _hash) {\n...
			CALLDATASIZE 			function ack(string _hash) {\n...
			SWAP5 			function ack(string _hash) {\n...
			SWAP3 			function ack(string _hash) {\n...
			SWAP4 			function ack(string _hash) {\n...
			PUSH 24			function ack(string _hash) {\n...
			SWAP4 			function ack(string _hash) {\n...
			SWAP3 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			SWAP2 			function ack(string _hash) {\n...
			SWAP1 			function ack(string _hash) {\n...
			DUP2 			function ack(string _hash) {\n...
			SWAP1 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			ADD 			function ack(string _hash) {\n...
			DUP4 			function ack(string _hash) {\n...
			DUP3 			function ack(string _hash) {\n...
			DUP1 			function ack(string _hash) {\n...
			DUP3 			function ack(string _hash) {\n...
			DUP5 			function ack(string _hash) {\n...
			CALLDATACOPY 			function ack(string _hash) {\n...
			POP 			
			SWAP5 			function ack(string _hash) {\n...
			SWAP8 			function ack(string _hash) {\n...
			POP 			
			PUSH [tag] 27			function ack(string _hash) {\n...
			SWAP7 			function ack(string _hash) {\n...
			POP 			
			POP 			
			POP 			
			POP 			
			POP 			
			POP 			
			POP 			
			JUMP 			function ack(string _hash) {\n...
		tag 6			string public hash_ack
			JUMPDEST 			string public hash_ack
			CALLVALUE 			string public hash_ack
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 28			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 28			a 
			JUMPDEST 			a 
			POP 			string public hash_ack
			PUSH [tag] 29			string public hash_ack
			PUSH [tag] 30			string public hash_ack
			JUMP 			string public hash_ack
		tag 29			string public hash_ack
			JUMPDEST 			string public hash_ack
			PUSH 40			string public hash_ack
			DUP1 			string public hash_ack
			MLOAD 			string public hash_ack
			PUSH 20			string public hash_ack
			DUP1 			string public hash_ack
			DUP3 			string public hash_ack
			MSTORE 			string public hash_ack
			DUP4 			string public hash_ack
			MLOAD 			string public hash_ack
			DUP2 			string public hash_ack
			DUP4 			string public hash_ack
			ADD 			string public hash_ack
			MSTORE 			string public hash_ack
			DUP4 			string public hash_ack
			MLOAD 			string public hash_ack
			SWAP2 			string public hash_ack
			SWAP3 			string public hash_ack
			DUP4 			string public hash_ack
			SWAP3 			string public hash_ack
			SWAP1 			string public hash_ack
			DUP4 			string public hash_ack
			ADD 			string public hash_ack
			SWAP2 			string public hash_ack
			DUP6 			string public hash_ack
			ADD 			string public hash_ack
			SWAP1 			string public hash_ack
			DUP1 			string public hash_ack
			DUP4 			string public hash_ack
			DUP4 			string public hash_ack
			PUSH 0			string public hash_ack
		tag 31			olidity 0.4.24;\n\n//Simple Ms...
			JUMPDEST 			olidity 0.4.24;\n\n//Simple Ms...
			DUP4 			 Ms
			DUP2 			p
			LT 			Simple Msg
			ISZERO 			olidity 0.4.24;\n\n//Simple Ms...
			PUSH [tag] 32			olidity 0.4.24;\n\n//Simple Ms...
			JUMPI 			olidity 0.4.24;\n\n//Simple Ms...
			DUP2 			ntract Mess
			DUP2 			ntract Mess
			ADD 			ntract Mess
			MLOAD 			n!)\ncontract Messa
			DUP4 			de validate
			DUP3 			de validate
			ADD 			de validate
			MSTORE 			t provide validateion!)\ncontr...
			PUSH 20			ra
			ADD 			 Registrar
			PUSH [tag] 31			olidity 0.4.24;\n\n//Simple Ms...
			JUMP 			olidity 0.4.24;\n\n//Simple Ms...
		tag 32			olidity 0.4.24;\n\n//Simple Ms...
			JUMPDEST 			olidity 0.4.24;\n\n//Simple Ms...
			POP 			ity 0.4.24;\n\n/
			POP 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			SWAP1 			string public hash_ack
			POP 			string public hash_ack
			SWAP1 			string public hash_ack
			DUP2 			string public hash_ack
			ADD 			string public hash_ack
			SWAP1 			string public hash_ack
			PUSH 1F			string public hash_ack
			AND 			string public hash_ack
			DUP1 			string public hash_ack
			ISZERO 			string public hash_ack
			PUSH [tag] 34			string public hash_ack
			JUMPI 			string public hash_ack
			DUP1 			string public hash_ack
			DUP3 			string public hash_ack
			SUB 			string public hash_ack
			DUP1 			string public hash_ack
			MLOAD 			string public hash_ack
			PUSH 1			string public hash_ack
			DUP4 			string public hash_ack
			PUSH 20			string public hash_ack
			SUB 			string public hash_ack
			PUSH 100			string public hash_ack
			EXP 			string public hash_ack
			SUB 			string public hash_ack
			NOT 			string public hash_ack
			AND 			string public hash_ack
			DUP2 			string public hash_ack
			MSTORE 			string public hash_ack
			PUSH 20			string public hash_ack
			ADD 			string public hash_ack
			SWAP2 			string public hash_ack
			POP 			string public hash_ack
		tag 34			string public hash_ack
			JUMPDEST 			string public hash_ack
			POP 			string public hash_ack
			SWAP3 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			PUSH 40			string public hash_ack
			MLOAD 			string public hash_ack
			DUP1 			string public hash_ack
			SWAP2 			string public hash_ack
			SUB 			string public hash_ack
			SWAP1 			string public hash_ack
			RETURN 			string public hash_ack
		tag 7			string public hash_msg
			JUMPDEST 			string public hash_msg
			CALLVALUE 			string public hash_msg
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 35			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 35			a 
			JUMPDEST 			a 
			POP 			string public hash_msg
			PUSH [tag] 29			string public hash_msg
			PUSH [tag] 37			string public hash_msg
			JUMP 			string public hash_msg
		tag 8			address public from
			JUMPDEST 			address public from
			CALLVALUE 			address public from
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 42			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 42			a 
			JUMPDEST 			a 
			POP 			address public from
			PUSH [tag] 20			address public from
			PUSH [tag] 44			address public from
			JUMP 			address public from
		tag 9			uint256 public timestamp_ack
			JUMPDEST 			uint256 public timestamp_ack
			CALLVALUE 			uint256 public timestamp_ack
			DUP1 			olidity 0
			ISZERO 			a 
			PUSH [tag] 45			a 
			JUMPI 			a 
			PUSH 0			p
			DUP1 			S
			REVERT 			24;\n\n//Simpl
		tag 45			a 
			JUMPDEST 			a 
			POP 			uint256 public timestamp_ack
			PUSH [tag] 17			uint256 public timestamp_ack
			PUSH [tag] 47			uint256 public timestamp_ack
			JUMP 			uint256 public timestamp_ack
		tag 18			uint256 public timestamp_msg
			JUMPDEST 			uint256 public timestamp_msg
			PUSH 5			uint256 public timestamp_msg
			SLOAD 			uint256 public timestamp_msg
			DUP2 			uint256 public timestamp_msg
			JUMP [out]			uint256 public timestamp_msg
		tag 21			address public to
			JUMPDEST 			address public to
			PUSH 2			address public to
			SLOAD 			address public to
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			AND 			address public to
			DUP2 			address public to
			JUMP [out]			address public to
		tag 24			address public registrar
			JUMPDEST 			address public registrar
			PUSH 0			address public registrar
			SLOAD 			address public registrar
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			AND 			address public registrar
			DUP2 			address public registrar
			JUMP [out]			address public registrar
		tag 27			function ack(string _hash) {\n...
			JUMPDEST 			function ack(string _hash) {\n...
			PUSH 2			to
			SLOAD 			to
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			AND 			to
			CALLER 			msg.sender
			EQ 			msg.sender!=to
			PUSH [tag] 49			if(msg.sender!=to) throw
			JUMPI 			if(msg.sender!=to) throw
			PUSH 0			throw
			DUP1 			throw
			REVERT 			throw
		tag 49			if(msg.sender!=to) throw
			JUMPDEST 			if(msg.sender!=to) throw
			PUSH 0			0
			PUSH 6			timestamp_ack
			SLOAD 			timestamp_ack
			GT 			timestamp_ack>0
			ISZERO 			if(timestamp_ack>0) throw
			PUSH [tag] 50			if(timestamp_ack>0) throw
			JUMPI 			if(timestamp_ack>0) throw
			PUSH 0			throw
			DUP1 			throw
			REVERT 			throw
		tag 50			if(timestamp_ack>0) throw
			JUMPDEST 			if(timestamp_ack>0) throw
			DUP1 			hash_ack=_hash
			MLOAD 			hash_ack=_hash
			PUSH [tag] 51			hash_ack=_hash
			SWAP1 			hash_ack=_hash
			PUSH 4			hash_ack
			SWAP1 			hash_ack
			PUSH 20			hash_ack=_hash
			DUP5 			hash_ack=_hash
			ADD 			hash_ack=_hash
			SWAP1 			hash_ack=_hash
			PUSH [tag] 52			hash_ack=_hash
			JUMP [in]			hash_ack=_hash
		tag 51			hash_ack=_hash
			JUMPDEST 			hash_ack=_hash
			POP 			
			POP 			
			TIMESTAMP 			now
			PUSH 6			timestamp_ack
			SSTORE 			timestamp_ack=now
			JUMP [out]			function ack(string _hash) {\n...
		tag 30			string public hash_ack
			JUMPDEST 			string public hash_ack
			PUSH 4			string public hash_ack
			DUP1 			string public hash_ack
			SLOAD 			string public hash_ack
			PUSH 40			string public hash_ack
			DUP1 			string public hash_ack
			MLOAD 			string public hash_ack
			PUSH 20			string public hash_ack
			PUSH 2			string public hash_ack
			PUSH 1			string public hash_ack
			DUP6 			string public hash_ack
			AND 			string public hash_ack
			ISZERO 			string public hash_ack
			PUSH 100			string public hash_ack
			MUL 			string public hash_ack
			PUSH 0			
			NOT 			
			ADD 			string public hash_ack
			SWAP1 			string public hash_ack
			SWAP5 			string public hash_ack
			AND 			string public hash_ack
			SWAP4 			string public hash_ack
			SWAP1 			string public hash_ack
			SWAP4 			string public hash_ack
			DIV 			string public hash_ack
			PUSH 1F			string public hash_ack
			DUP2 			string public hash_ack
			ADD 			string public hash_ack
			DUP5 			string public hash_ack
			SWAP1 			string public hash_ack
			DIV 			string public hash_ack
			DUP5 			string public hash_ack
			MUL 			string public hash_ack
			DUP3 			string public hash_ack
			ADD 			string public hash_ack
			DUP5 			string public hash_ack
			ADD 			string public hash_ack
			SWAP1 			string public hash_ack
			SWAP3 			string public hash_ack
			MSTORE 			string public hash_ack
			DUP2 			string public hash_ack
			DUP2 			string public hash_ack
			MSTORE 			string public hash_ack
			SWAP3 			string public hash_ack
			SWAP2 			string public hash_ack
			DUP4 			string public hash_ack
			ADD 			string public hash_ack
			DUP3 			string public hash_ack
			DUP3 			string public hash_ack
			DUP1 			string public hash_ack
			ISZERO 			string public hash_ack
			PUSH [tag] 53			string public hash_ack
			JUMPI 			string public hash_ack
			DUP1 			string public hash_ack
			PUSH 1F			string public hash_ack
			LT 			string public hash_ack
			PUSH [tag] 54			string public hash_ack
			JUMPI 			string public hash_ack
			PUSH 100			string public hash_ack
			DUP1 			string public hash_ack
			DUP4 			string public hash_ack
			SLOAD 			string public hash_ack
			DIV 			string public hash_ack
			MUL 			string public hash_ack
			DUP4 			string public hash_ack
			MSTORE 			string public hash_ack
			SWAP2 			string public hash_ack
			PUSH 20			string public hash_ack
			ADD 			string public hash_ack
			SWAP2 			string public hash_ack
			PUSH [tag] 53			string public hash_ack
			JUMP 			string public hash_ack
		tag 54			string public hash_ack
			JUMPDEST 			string public hash_ack
			DUP3 			string public hash_ack
			ADD 			string public hash_ack
			SWAP2 			string public hash_ack
			SWAP1 			string public hash_ack
			PUSH 0			string public hash_ack
			MSTORE 			string public hash_ack
			PUSH 20			string public hash_ack
			PUSH 0			string public hash_ack
			KECCAK256 			string public hash_ack
			SWAP1 			string public hash_ack
		tag 55			string public hash_ack
			JUMPDEST 			string public hash_ack
			DUP2 			string public hash_ack
			SLOAD 			string public hash_ack
			DUP2 			string public hash_ack
			MSTORE 			string public hash_ack
			SWAP1 			string public hash_ack
			PUSH 1			string public hash_ack
			ADD 			string public hash_ack
			SWAP1 			string public hash_ack
			PUSH 20			string public hash_ack
			ADD 			string public hash_ack
			DUP1 			string public hash_ack
			DUP4 			string public hash_ack
			GT 			string public hash_ack
			PUSH [tag] 55			string public hash_ack
			JUMPI 			string public hash_ack
			DUP3 			string public hash_ack
			SWAP1 			string public hash_ack
			SUB 			string public hash_ack
			PUSH 1F			string public hash_ack
			AND 			string public hash_ack
			DUP3 			string public hash_ack
			ADD 			string public hash_ack
			SWAP2 			string public hash_ack
		tag 53			string public hash_ack
			JUMPDEST 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			POP 			string public hash_ack
			DUP2 			string public hash_ack
			JUMP [out]			string public hash_ack
		tag 37			string public hash_msg
			JUMPDEST 			string public hash_msg
			PUSH 3			string public hash_msg
			DUP1 			string public hash_msg
			SLOAD 			string public hash_msg
			PUSH 40			string public hash_msg
			DUP1 			string public hash_msg
			MLOAD 			string public hash_msg
			PUSH 20			string public hash_msg
			PUSH 2			string public hash_msg
			PUSH 1			string public hash_msg
			DUP6 			string public hash_msg
			AND 			string public hash_msg
			ISZERO 			string public hash_msg
			PUSH 100			string public hash_msg
			MUL 			string public hash_msg
			PUSH 0			
			NOT 			
			ADD 			string public hash_msg
			SWAP1 			string public hash_msg
			SWAP5 			string public hash_msg
			AND 			string public hash_msg
			SWAP4 			string public hash_msg
			SWAP1 			string public hash_msg
			SWAP4 			string public hash_msg
			DIV 			string public hash_msg
			PUSH 1F			string public hash_msg
			DUP2 			string public hash_msg
			ADD 			string public hash_msg
			DUP5 			string public hash_msg
			SWAP1 			string public hash_msg
			DIV 			string public hash_msg
			DUP5 			string public hash_msg
			MUL 			string public hash_msg
			DUP3 			string public hash_msg
			ADD 			string public hash_msg
			DUP5 			string public hash_msg
			ADD 			string public hash_msg
			SWAP1 			string public hash_msg
			SWAP3 			string public hash_msg
			MSTORE 			string public hash_msg
			DUP2 			string public hash_msg
			DUP2 			string public hash_msg
			MSTORE 			string public hash_msg
			SWAP3 			string public hash_msg
			SWAP2 			string public hash_msg
			DUP4 			string public hash_msg
			ADD 			string public hash_msg
			DUP3 			string public hash_msg
			DUP3 			string public hash_msg
			DUP1 			string public hash_msg
			ISZERO 			string public hash_msg
			PUSH [tag] 53			string public hash_msg
			JUMPI 			string public hash_msg
			DUP1 			string public hash_msg
			PUSH 1F			string public hash_msg
			LT 			string public hash_msg
			PUSH [tag] 54			string public hash_msg
			JUMPI 			string public hash_msg
			PUSH 100			string public hash_msg
			DUP1 			string public hash_msg
			DUP4 			string public hash_msg
			SLOAD 			string public hash_msg
			DIV 			string public hash_msg
			MUL 			string public hash_msg
			DUP4 			string public hash_msg
			MSTORE 			string public hash_msg
			SWAP2 			string public hash_msg
			PUSH 20			string public hash_msg
			ADD 			string public hash_msg
			SWAP2 			string public hash_msg
			PUSH [tag] 53			string public hash_msg
			JUMP 			string public hash_msg
		tag 44			address public from
			JUMPDEST 			address public from
			PUSH 1			address public from
			SLOAD 			address public from
			PUSH 1			
			PUSH A0			
			PUSH 2			
			EXP 			
			SUB 			
			AND 			address public from
			DUP2 			address public from
			JUMP [out]			address public from
		tag 47			uint256 public timestamp_ack
			JUMPDEST 			uint256 public timestamp_ack
			PUSH 6			uint256 public timestamp_ack
			SLOAD 			uint256 public timestamp_ack
			DUP2 			uint256 public timestamp_ack
			JUMP [out]			uint256 public timestamp_ack
		tag 52			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			SLOAD 			contract Message {\n\taddress ...
			PUSH 1			contract Message {\n\taddress ...
			DUP2 			contract Message {\n\taddress ...
			PUSH 1			contract Message {\n\taddress ...
			AND 			contract Message {\n\taddress ...
			ISZERO 			contract Message {\n\taddress ...
			PUSH 100			contract Message {\n\taddress ...
			MUL 			contract Message {\n\taddress ...
			SUB 			contract Message {\n\taddress ...
			AND 			contract Message {\n\taddress ...
			PUSH 2			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			DIV 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			PUSH 0			contract Message {\n\taddress ...
			MSTORE 			contract Message {\n\taddress ...
			PUSH 20			contract Message {\n\taddress ...
			PUSH 0			contract Message {\n\taddress ...
			KECCAK256 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			PUSH 1F			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			PUSH 20			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			DIV 			contract Message {\n\taddress ...
			DUP2 			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			SWAP3 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			PUSH 1F			contract Message {\n\taddress ...
			LT 			contract Message {\n\taddress ...
			PUSH [tag] 60			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			MLOAD 			contract Message {\n\taddress ...
			PUSH FF			contract Message {\n\taddress ...
			NOT 			contract Message {\n\taddress ...
			AND 			contract Message {\n\taddress ...
			DUP4 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			OR 			contract Message {\n\taddress ...
			DUP6 			contract Message {\n\taddress ...
			SSTORE 			contract Message {\n\taddress ...
			PUSH [tag] 62			contract Message {\n\taddress ...
			JUMP 			contract Message {\n\taddress ...
		tag 60			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			PUSH 1			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			DUP6 			contract Message {\n\taddress ...
			SSTORE 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			ISZERO 			contract Message {\n\taddress ...
			PUSH [tag] 62			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			SWAP2 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
		tag 61			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			DUP2 			contract Message {\n\taddress ...
			GT 			contract Message {\n\taddress ...
			ISZERO 			contract Message {\n\taddress ...
			PUSH [tag] 62			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			MLOAD 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			SSTORE 			contract Message {\n\taddress ...
			SWAP2 			contract Message {\n\taddress ...
			PUSH 20			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			SWAP2 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			PUSH 1			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			PUSH [tag] 61			contract Message {\n\taddress ...
			JUMP 			contract Message {\n\taddress ...
		tag 62			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			POP 			
			PUSH [tag] 63			contract Message {\n\taddress ...
			SWAP3 			contract Message {\n\taddress ...
			SWAP2 			contract Message {\n\taddress ...
			POP 			
			PUSH [tag] 64			contract Message {\n\taddress ...
			JUMP [in]			contract Message {\n\taddress ...
		tag 63			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			POP 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			JUMP [out]			contract Message {\n\taddress ...
		tag 64			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			PUSH [tag] 65			contract Message {\n\taddress ...
			SWAP2 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
		tag 66			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			DUP1 			contract Message {\n\taddress ...
			DUP3 			contract Message {\n\taddress ...
			GT 			contract Message {\n\taddress ...
			ISZERO 			contract Message {\n\taddress ...
			PUSH [tag] 63			contract Message {\n\taddress ...
			JUMPI 			contract Message {\n\taddress ...
			PUSH 0			contract Message {\n\taddress ...
			DUP2 			contract Message {\n\taddress ...
			SSTORE 			contract Message {\n\taddress ...
			PUSH 1			contract Message {\n\taddress ...
			ADD 			contract Message {\n\taddress ...
			PUSH [tag] 66			contract Message {\n\taddress ...
			JUMP 			contract Message {\n\taddress ...
		tag 65			contract Message {\n\taddress ...
			JUMPDEST 			contract Message {\n\taddress ...
			SWAP1 			contract Message {\n\taddress ...
			JUMP [out]			contract Message {\n\taddress ...
		.data
